#!/bin/bash

# MariaDB is running as user mysql, so choose a path
# which mysql is allowed to write to.
cat <<EOF > /var/lib/mysql/pma.sql
CREATE USER IF NOT EXISTS 'pma'@'%';

ALTER USER 'pma'@'%' IDENTIFIED BY PASSWORD '${MARIADB_PASSWORD_HASH}';
ALTER USER 'pma'@'%' PASSWORD EXPIRE NEVER;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, PROCESS, FILE, REFERENCES,
	INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES,
	CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON *.* TO 'pma'@'%';
EOF
