name: docker-lamp

on:
  pull_request:
  push:
    branches:
    - 'main'
    - 'bug/**'
    - 'feature/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lamp:
    strategy:
      matrix:
        envfile:
          - "env_php-7.4.33_mariadb-10.6.19"
          - "env_php-8.3.11_mariadb-11.2.4"
        flavour:
          - simple
          - simple-htmldir
          - development

    name: ${{ matrix.envfile }}-${{ matrix.flavour }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create certificates
        run: |
          set -euo pipefail

          ./mkcerts.sh
          # View created files
          find certs/ -printf "%M %p\n" | sort -k 1.12

      # Run the production version
      - name: Build and run docker images
        if: matrix.flavour == 'simple'
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
        run: |
            docker compose up --detach

      # Run the production version with custom HTMLDIR
      - name: Build and run docker images
        if: matrix.flavour == 'simple-htmldir'
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
          HTMLDIR: ./html
        run: |
            mkdir "$HTMLDIR"
            echo "It works" > "$HTMLDIR/index.html"

            docker compose up --detach

      # Run the development version
      - name: Build and run docker images
        if: matrix.flavour == 'development'
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
        run: |
            ${GITHUB_WORKSPACE}/docker-compose-devel up --detach

      - name: Wait for startup
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
        run: |
          # Wait for startup of services by parsing output and
          # exiting awk if all conditions are met
          timeout 10 awk 'BEGIN { apache = mariadb = temp = 0 }

            /AH00094: Command line/ { apache = 1 }

            /Starting temporary server/ { temp = 1 }
            /Temporary server stopped/ { temp = 0 }

            /mariadbd: ready for connections./ {
              if (!temp)
                mariadb = 1
            }

            { print $0 }

            apache == 1 && mariadb == 1 { exit 0 }
          ' <(docker compose logs --follow apache mariadb)

      # As only test we should get back what we echo'ed into the index file above
      - name: Run test
        if: matrix.flavour == 'simple-htmldir'
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
          HTMLDIR: ./html
        run: |
          curl -sS --cacert certs/ca-cert.crt https://localhost | grep "It works"

      # Run the test script -- in trace mode to see what is about to happen...
      - name: Run test
        if: matrix.flavour != 'simple-htmldir'
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
          HTMLDIR: ./html
        run: |
          bash -x ${GITHUB_WORKSPACE}/test.sh

      - name: Stop containers
        if: always()
        env:
          COMPOSE_ENV_FILES: ${{ matrix.envfile }}
        run: |
          source $COMPOSE_ENV_FILES

          docker compose down
          docker volume rm --force "${PROJECT_NAME}*"
